# Generated by Django 3.0.7 on 2020-06-17 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Site',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('category', models.CharField(max_length=50)),
                ('interest', models.CharField(max_length=50)),
                ('subcategory', models.CharField(max_length=50)),
                ('organisation', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=100)),
                ('website', models.CharField(max_length=100)),
                ('lat', models.DecimalField(decimal_places=6, max_digits=9)),
                ('lon', models.DecimalField(decimal_places=6, max_digits=9)),
                ('description', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Waypoint',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('lat', models.DecimalField(decimal_places=6, max_digits=9)),
                ('lon', models.DecimalField(decimal_places=6, max_digits=9)),
            ],
        ),
        migrations.CreateModel(
            name='Route',
            fields=[
                ('name', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('waypoints', models.ManyToManyField(to='tours.Waypoint')),
            ],
        ),
    ]
