# Generated by Django 3.0.7 on 2020-07-06 01:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Route',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('_operator', models.CharField(max_length=32)),
                ('_short_name', models.CharField(max_length=16)),
                ('_direction', models.CharField(max_length=48)),
                ('type', models.CharField(choices=[('B', 'Bus route'), ('C', 'Cycle route')], max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Site',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('category', models.CharField(max_length=50)),
                ('interest', models.CharField(max_length=50)),
                ('subcategory', models.CharField(max_length=50)),
                ('organisation', models.CharField(blank=True, max_length=50)),
                ('address', models.CharField(max_length=100)),
                ('website', models.CharField(blank=True, max_length=100)),
                ('lat', models.DecimalField(decimal_places=6, max_digits=9)),
                ('lon', models.DecimalField(decimal_places=6, max_digits=9)),
                ('description', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Waypoint',
            fields=[
                ('id', models.CharField(max_length=9, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('lat', models.DecimalField(decimal_places=6, max_digits=9)),
                ('lon', models.DecimalField(decimal_places=6, max_digits=9)),
                ('type', models.CharField(choices=[('B', 'Bus route'), ('C', 'Cycle route')], max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='WaypointOnRoute',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_beginning', models.BooleanField(default=False)),
                ('is_end', models.BooleanField(default=False)),
                ('next', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='previous', to='tours.WaypointOnRoute')),
                ('route', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tours.Route')),
                ('waypoint', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tours.Waypoint')),
            ],
        ),
        migrations.AddField(
            model_name='route',
            name='first_stop',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='starts_routes', to='tours.WaypointOnRoute'),
        ),
        migrations.AddField(
            model_name='route',
            name='last_stop',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ends_routes', to='tours.WaypointOnRoute'),
        ),
        migrations.AddField(
            model_name='route',
            name='waypoints',
            field=models.ManyToManyField(related_name='on_routes', to='tours.WaypointOnRoute'),
        ),
    ]
