# Generated by Django 3.0.7 on 2020-09-01 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='waypointonroute',
            name='num',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
