# Generated by Django 3.0.7 on 2020-06-23 03:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='site',
            old_name='id',
            new_name='site_id',
        ),
        migrations.AddField(
            model_name='route',
            name='short_name',
            field=models.CharField(default='-', max_length=16),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='route',
            name='type',
            field=models.CharField(choices=[('B', 'Bus route'), ('C', 'Cycle route')], default='-', max_length=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='waypoint',
            name='is_one_way',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='waypoint',
            name='type',
            field=models.CharField(choices=[('B', 'Bus route'), ('C', 'Cycle route')], default='-', max_length=1),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='WaypointOnRoute',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_beginning', models.BooleanField(default=False)),
                ('is_end', models.BooleanField(default=False)),
                ('next', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='previous', to='tours.WaypointOnRoute')),
                ('route', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tours.Route')),
                ('waypoint', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tours.Waypoint')),
            ],
        ),
        migrations.AlterField(
            model_name='route',
            name='waypoints',
            field=models.ManyToManyField(related_name='on_routes', to='tours.WaypointOnRoute'),
        ),
    ]
