# Generated by Django 3.0.7 on 2020-09-01 06:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0002_waypointonroute_num'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='waypointonroute',
            name='num',
        ),
    ]
