# Generated by Django 3.0.7 on 2020-06-23 06:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0002_auto_20200623_0322'),
    ]

    operations = [
        migrations.AddField(
            model_name='route',
            name='first_stop',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='starts_routes', to='tours.WaypointOnRoute'),
        ),
        migrations.AddField(
            model_name='route',
            name='last_stop',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ends_routes', to='tours.WaypointOnRoute'),
        ),
    ]
