# Generated by Django 3.0.7 on 2020-06-23 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0003_auto_20200623_0647'),
    ]

    operations = [
        migrations.RenameField(
            model_name='site',
            old_name='site_id',
            new_name='id',
        ),
        migrations.RemoveField(
            model_name='waypoint',
            name='is_one_way',
        ),
        migrations.AddField(
            model_name='route',
            name='is_one_way',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='site',
            name='website',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='waypoint',
            name='id',
            field=models.CharField(max_length=9, primary_key=True, serialize=False),
        ),
    ]
