# Generated by Django 3.0.7 on 2021-07-04 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0003_remove_waypointonroute_num'),
    ]

    operations = [
        migrations.AddField(
            model_name='waypointonroute',
            name='is_key',
            field=models.BooleanField(default=False),
        ),
    ]
