# Generated by Django 3.0.7 on 2020-06-24 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0004_auto_20200623_1149'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='route',
            name='is_one_way',
        ),
        migrations.AddField(
            model_name='route',
            name='direction',
            field=models.CharField(default='-', max_length=48),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='route',
            name='operator',
            field=models.CharField(default='-', max_length=32),
            preserve_default=False,
        ),
    ]
