# Generated by Django 3.0.7 on 2021-07-04 20:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0004_waypointonroute_is_key'),
    ]

    operations = [
        migrations.RenameField(
            model_name='waypointonroute',
            old_name='is_key',
            new_name='is_keypoint',
        ),
    ]
